# Generated by Django 4.0.3 on 2022-10-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_license',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='carsbrand',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='carsmodel',
            unique_together={('car_brand', 'name', 'year')},
        ),
    ]
