# Generated by Django 4.1.1 on 2022-11-21 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.town'),
        ),
        migrations.AddField(
            model_name='occupationranges',
            name='occupation_range_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.occupationrangestype'),
        ),
        migrations.AddField(
            model_name='occupationranges',
            name='related_publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.publication'),
        ),
        migrations.AlterUniqueTogether(
            name='localizations',
            unique_together={('latitude', 'longitude')},
        ),
        migrations.AlterUniqueTogether(
            name='occupationranges',
            unique_together={('start_date', 'end_date', 'related_publication')},
        ),
    ]
