# Generated by Django 4.1.1 on 2022-11-21 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupationRepeatMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'RepeatMode',
                'verbose_name_plural': 'RepeatModes',
            },
        ),
        migrations.AddField(
            model_name='occupationranges',
            name='repeat_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.occupationrepeatmode'),
        ),
    ]
