# Generated by Django 4.1.1 on 2022-11-21 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookingstatus_remove_bookings_cancelled_and_more'),
        ('publications', '0003_occupationrepeatmode_occupationranges_repeat_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupationranges',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.bookings'),
        ),
        migrations.AlterField(
            model_name='occupationranges',
            name='occupation_range_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='publications.occupationrangestype'),
        ),
        migrations.AlterField(
            model_name='occupationranges',
            name='repeat_mode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='publications.occupationrepeatmode'),
        ),
    ]
