# Generated by Django 4.1.1 on 2022-11-19 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('data_resolution', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Feedback Report',
                'verbose_name_plural': 'Feedback Reports',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('image', models.TextField(blank=True, null=True)),
                ('data_reported', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='TypeResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Type Resolution',
                'verbose_name_plural': 'Type Resolutions',
            },
        ),
        migrations.CreateModel(
            name='SectionReportPublication',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.report')),
            ],
            options={
                'verbose_name': 'Section Report Publication',
                'verbose_name_plural': 'Section Report Publications',
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='SectionReportUser',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.report')),
            ],
            options={
                'verbose_name': 'Section Report User',
                'verbose_name_plural': 'Section Report Users',
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='SectionReportValoration',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.report')),
            ],
            options={
                'verbose_name': 'Section Report Valoration',
                'verbose_name_plural': 'Section Report Valorations',
            },
            bases=('reports.report',),
        ),
    ]
