# Generated by Django 4.1.1 on 2022-11-21 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
        ('publications', '0002_initial'),
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackreport',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackreport',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report'),
        ),
        migrations.AddField(
            model_name='feedbackreport',
            name='resolution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.typeresolution'),
        ),
        migrations.AddField(
            model_name='sectionreportvaloration',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.bookings'),
        ),
        migrations.AddField(
            model_name='sectionreportuser',
            name='reported_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sectionreportpublication',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.publication'),
        ),
    ]
