AWSTemplateFormatVersion : "2010-09-09"

Transform: AWS::Serverless-2016-10-31

Resources:
################################################
#                Resources for EC2             #
################################################
  GreenWheelEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0f29c8402f8cce65c
      SecurityGroups: [default]
      Tags:
        - Key: Name
          Value: EC2

  ################################################
  #           Resources for S3 Bucket            #
  ################################################
  GreenWheelS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: pes-bucket

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref GreenWheelS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 's3:*'
            Resource:
              - !Sub 'arn:aws:s3:::${GreenWheelS3Bucket}'
              - !Sub 'arn:aws:s3:::${GreenWheelS3Bucket}/*'