AWSTemplateFormatVersion : "2010-09-09"

Transform: AWS::Serverless-2016-10-31

Resources:
################################################
#                Resources for EC2             #
################################################
  GreenWheelEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0f29c8402f8cce65c
      SecurityGroups: [default]
      Tags:
        - Key: Name
          Value: EC2