AWSTemplateFormatVersion : "2010-09-09"

Parameters:
  VpcCIDR:
    Description: IP range (CIDR notation) for this VPC
    Type: String
    Default: 172.31.0.0/16

Transform: AWS::Serverless-2016-10-31

Resources:
################################################
#                Resources for EC2             #
################################################
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access from the VPC
      VpcId: default

  InstanceIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SecurityGroup
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      SourceSecurityGroupId: !GetAtt SecurityGroup.GroupId

  EC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0f29c8402f8cce65c
      Tags:
        - Key: Name
          Value: EC2
      SecurityGroupIds:
        - !GetAtt SecurityGroup.GroupId
