AWSTemplateFormatVersion : "2010-09-09"

Transform: AWS::Serverless-2016-10-31

Parameters:
  DBAllocatedStorage:
    Default: '50'
    Description: The size of the database (GiB)
    Type: Number
    MinValue: '20'
    MaxValue: '65536'
    ConstraintDescription: must be between 20 and 65536 GiB.
  DBUsername:
    NoEcho: 'true'
    Description: Username for MySQL database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    NoEcho: 'true'
    Description: Password MySQL database access
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
  TcpPort:
    Description: Enter RDS Listening TCP Port number.
    Type: Number
    Default: '5432'

Resources:
################################################
#                Resources for EC2             #
################################################
  GreenWheelEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0f29c8402f8cce65c
      SecurityGroups: [default]
      Tags:
        - Key: Name
          Value: EC2
      UserData: !Base64 |
        #!/bin/bash
        # Install Docker
        sudo yum update -y
        sudo yum install docker -y
        sudo service docker start
        sudo usermod -a -G docker ec2-user
        # Install docker-compose
        sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        # Create docker-compose file
        echo "
        version: '3.9'
        services:
          backend-app:
            container_name: backend_app
            image: crismigo/greenwheel_backend:latest
            restart: always
            ports:
              - "80:8000"
            environment:
              DJANGO_SECRET_KEY=cnc+sy7tn*=0^hc#^hm7=cf&@oicx+g4-fmpsm1$i3dpcp3^hu
              DJANGO_DATABASE_HOST=localhost
              DJANGO_DATABASE_PORT=5432
              DJANGO_DATABASE_NAME=GreenWheelDB
              DJANGO_DATABASE_USER=greenwheel
              DJANGO_DATABASE_PASSWORD=!Ref DBPassword
        " > docker-compose.yml
        # Run docker-compose
        sudo /usr/local/bin/docker-compose up -d

  ################################################
  #           Resources for S3 Bucket            #
  ################################################
  GreenWheelS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: greenwheel-bucket

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref GreenWheelS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - 's3:*'
            Resource:
              - !Sub 'arn:aws:s3:::${GreenWheelS3Bucket}'
              - !Sub 'arn:aws:s3:::${GreenWheelS3Bucket}/*'

  ################################################
  #           Resources for RDS                  #
  ################################################
  GreenWheelDB:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      BackupRetentionPeriod: 5
      DBInstanceIdentifier: !Ref AWS::StackName
      DBName: "GreenWheelDB"
      DBInstanceClass: db.t2.micro
      AllocatedStorage: '5'
      Engine: postgres
      EngineVersion: "12.12"
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      Port: '5432'
      VPCSecurityGroups: [sg-09b6ca72aa4c8436a]
