version: '3.9'

services:
  db:
    image: postgres:14.5
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: greenwheel_user
      POSTGRES_PASSWORD: GreenWheel
      POSTGRES_DB: greenwheel
    volumes:
      - db_data:/var/lib/postgresql/data

  greenwheel-app:
    container_name: greenwheel_app
    image: customer-ec2:latest
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - customer-ec2-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/customers
volumes:
  db_data:
