# Generated by Django 4.1.1 on 2022-11-19 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='user_recived',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_recived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chats',
            name='user_sent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
