# Generated by Django 4.1.1 on 2022-11-04 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chargers', '0003_alter_privatechargers_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chargers.publication')),
            ],
            options={
                'verbose_name': 'Bike',
                'verbose_name_plural': 'Bikes',
            },
            bases=('chargers.publication',),
        ),
        migrations.CreateModel(
            name='BikeTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'BikeType',
                'verbose_name_plural': 'BikeTypes',
            },
        ),
        migrations.CreateModel(
            name='ElectricBikes',
            fields=[
                ('bikes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bikes.bikes')),
                ('power', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'ElectricBike',
                'verbose_name_plural': 'ElectricBikes',
            },
            bases=('bikes.bikes',),
        ),
        migrations.AddField(
            model_name='bikes',
            name='bike_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.biketypes'),
        ),
    ]
