# Generated by Django 4.1.1 on 2022-10-01 19:40

from django.db import migrations

def load_initial_data(apps, schema_editor):
    # get our model
    # get_model(appname, modelname)
    language_model = apps.get_model('users', 'Languages')
    language_model.objects.create (
        name = "Catala", shortname = "ca"
        )
    language_model.objects.create(
        name="Castellano", shortname="es"
    )
    language_model.objects.create(
        name="English", shortname="en"
    )
    login_methods = apps.get_model('users', 'LoginMethods')
    login_methods.objects.create(
        name="native")
    login_methods.objects.create(
        name="google")
    login_methods.objects.create(
        name="raco")

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
