# Generated by Django 4.1.1 on 2022-10-13 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221001_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='users',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='login_method',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.loginmethods'),
        ),
    ]
