# Generated by Django 4.1.1 on 2022-10-01 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221001_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languages',
            name='id',
        ),
        migrations.AlterField(
            model_name='languages',
            name='shortname',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='language',
            field=models.ForeignKey(blank=True, default='es', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.languages'),
        ),
        migrations.AlterField(
            model_name='users',
            name='login_method',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.loginmethods'),
        ),
    ]
