# Generated by Django 4.1.1 on 2022-10-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_languages_id_alter_languages_shortname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='shortname',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
