# Generated by Django 4.1.1 on 2022-10-01 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_languages_shortname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='language',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.languages'),
        ),
    ]
