# Generated by Django 4.1.1 on 2022-10-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_users_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='users',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
