# Generated by Django 4.1.1 on 2022-11-21 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0002_initial'),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='ratings',
            constraint=models.CheckConstraint(check=models.Q(('rate__gte', 0), ('rate__lte', 5)), name='rate_check'),
        ),
        migrations.AlterUniqueTogether(
            name='ratings',
            unique_together={('user', 'booking')},
        ),
        migrations.AddField(
            model_name='postrating',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.publication'),
        ),
        migrations.AddField(
            model_name='clientsrating',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
