# Generated by Django 4.1.1 on 2022-11-19 20:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0005_alter_bookings_confirmed_alter_bookings_end_date'),
        ('ratings', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postrating',
            options={'verbose_name': 'Publication Rating', 'verbose_name_plural': 'Publications Ratings'},
        ),
        migrations.AlterUniqueTogether(
            name='ratings',
            unique_together={('user', 'booking')},
        ),
    ]
