# Generated by Django 4.1.1 on 2022-11-20 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_ratings_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientsrating',
            options={'verbose_name': 'Client Rating', 'verbose_name_plural': 'Clients Ratings'},
        ),
    ]
