# Generated by Django 4.1.1 on 2022-10-04 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('direction', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Localization',
                'verbose_name_plural': 'Localizations',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('latitude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='chargers.localizations')),
                ('longitude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='chargers.localizations')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
            },
        ),
        migrations.CreateModel(
            name='TypeCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'TypeCurrent',
                'verbose_name_plural': 'TypeCurrents',
            },
        ),
        migrations.CreateModel(
            name='TypeSpeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'TypeSpeed',
                'verbose_name_plural': 'TypeSpeeds',
            },
        ),
        migrations.CreateModel(
            name='TypeVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'TypeVehicle',
                'verbose_name_plural': 'TypeVehicles',
            },
        ),
        migrations.CreateModel(
            name='Chargers',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chargers.publication')),
                ('power', models.FloatField()),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Charger',
                'verbose_name_plural': 'Chargers',
            },
            bases=('chargers.publication',),
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chargers.province')),
            ],
            options={
                'verbose_name': 'Town',
                'verbose_name_plural': 'Towns',
            },
        ),
        migrations.AddField(
            model_name='localizations',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chargers.town'),
        ),
        migrations.CreateModel(
            name='ChargersType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('current', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chargers.typecurrent')),
                ('type_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chargers.typevehicle')),
            ],
            options={
                'verbose_name': 'ChargerType',
                'verbose_name_plural': 'ChargersType',
            },
        ),
        migrations.CreateModel(
            name='PublicChargers',
            fields=[
                ('chargers_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chargers.chargers')),
                ('agent', models.CharField(max_length=50)),
                ('identifier', models.CharField(max_length=50)),
                ('access', models.CharField(max_length=50)),
            ],
            bases=('chargers.chargers',),
        ),
        migrations.AlterUniqueTogether(
            name='localizations',
            unique_together={('latitude', 'longitude')},
        ),
        migrations.AddField(
            model_name='chargers',
            name='charger_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chargers.chargerstype'),
        ),
        migrations.AddField(
            model_name='chargers',
            name='speed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chargers.typespeed'),
        ),
    ]
