# Generated by Django 4.1.1 on 2022-11-21 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chargers',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publications.publication')),
                ('power', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'Charger',
                'verbose_name_plural': 'Chargers',
            },
            bases=('publications.publication',),
        ),
        migrations.CreateModel(
            name='Configs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Config',
                'verbose_name_plural': 'Configs',
            },
        ),
        migrations.CreateModel(
            name='ConnectionsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'ConnectionsType',
                'verbose_name_plural': 'ConnectionsTypes',
            },
        ),
        migrations.CreateModel(
            name='CurrentsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'CurrentsType',
                'verbose_name_plural': 'CurrentsTypes',
            },
        ),
        migrations.CreateModel(
            name='SpeedsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'SpeedsType',
                'verbose_name_plural': 'SpeedsTypes',
            },
        ),
        migrations.CreateModel(
            name='PrivateChargers',
            fields=[
                ('chargers_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chargers.chargers')),
                ('price', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'PrivateCharger',
                'verbose_name_plural': 'PrivateChargers',
            },
            bases=('chargers.chargers',),
        ),
        migrations.CreateModel(
            name='PublicChargers',
            fields=[
                ('chargers_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chargers.chargers')),
                ('agent', models.TextField(null=True)),
                ('identifier', models.CharField(max_length=50, null=True)),
                ('access', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'PublicCharger',
                'verbose_name_plural': 'PublicChargers',
            },
            bases=('chargers.chargers',),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.publication')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.AddField(
            model_name='chargers',
            name='connection_type',
            field=models.ManyToManyField(to='chargers.connectionstype'),
        ),
        migrations.AddField(
            model_name='chargers',
            name='current_type',
            field=models.ManyToManyField(to='chargers.currentstype'),
        ),
        migrations.AddField(
            model_name='chargers',
            name='speed',
            field=models.ManyToManyField(to='chargers.speedstype'),
        ),
    ]
