# Generated by Django 4.1.1 on 2022-11-19 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chargers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chargers.town'),
        ),
        migrations.AddField(
            model_name='occupationranges',
            name='occupation_range_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chargers.occupationrangestype'),
        ),
        migrations.AddField(
            model_name='occupationranges',
            name='related_publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chargers.publication'),
        ),
        migrations.AlterUniqueTogether(
            name='localizations',
            unique_together={('latitude', 'longitude')},
        ),
        migrations.CreateModel(
            name='PrivateChargers',
            fields=[
                ('chargers_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chargers.chargers')),
                ('price', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'PrivateCharger',
                'verbose_name_plural': 'PrivateChargers',
            },
            bases=('chargers.chargers',),
        ),
        migrations.CreateModel(
            name='PublicChargers',
            fields=[
                ('chargers_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chargers.chargers')),
                ('agent', models.TextField(null=True)),
                ('identifier', models.CharField(max_length=50, null=True)),
                ('access', models.CharField(max_length=50, null=True)),
                ('available', models.BooleanField(default=True, null=True)),
            ],
            options={
                'verbose_name': 'PublicCharger',
                'verbose_name_plural': 'PublicChargers',
            },
            bases=('chargers.chargers',),
        ),
        migrations.AlterUniqueTogether(
            name='occupationranges',
            unique_together={('start_date', 'end_date', 'related_publication')},
        ),
        migrations.AddField(
            model_name='chargers',
            name='connection_type',
            field=models.ManyToManyField(to='chargers.connectionstype'),
        ),
        migrations.AddField(
            model_name='chargers',
            name='current_type',
            field=models.ManyToManyField(to='chargers.currentstype'),
        ),
        migrations.AddField(
            model_name='chargers',
            name='speed',
            field=models.ManyToManyField(to='chargers.speedstype'),
        ),
    ]
