# Generated by Django 4.1.1 on 2022-10-20 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0002_auto_20221020_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatechargers',
            options={'verbose_name': 'PrivateCharger', 'verbose_name_plural': 'PrivateChargers'},
        ),
        migrations.AlterModelOptions(
            name='publicchargers',
            options={'verbose_name': 'PublicCharger', 'verbose_name_plural': 'PublicChargers'},
        ),
        migrations.RemoveField(
            model_name='chargers',
            name='available',
        ),
        migrations.RemoveField(
            model_name='localizations',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='localizations',
            name='town',
        ),
        migrations.AddField(
            model_name='publication',
            name='direction',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chargers.town'),
        ),
        migrations.AddField(
            model_name='publicchargers',
            name='available',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicchargers',
            name='agent',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='town',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
