# Generated by Django 4.1.1 on 2022-11-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargers',
            name='power',
            field=models.FloatField(null=True),
        ),
    ]
