# Generated by Django 4.1.1 on 2022-11-04 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0004_remove_bookings_rating'),
        ('chargers', '0003_alter_privatechargers_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupationRangesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'OccupationRangesType',
                'verbose_name_plural': 'OccupationRangesTypes',
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OccupationRanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('occupation_range_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chargers.occupationrangestype')),
                ('related_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.bookings')),
                ('related_publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chargers.publication')),
            ],
            options={
                'verbose_name': 'OccupationRange',
                'verbose_name_plural': 'OccupationRanges',
                'unique_together': {('start_date', 'end_date', 'related_publication')},
            },
        ),
    ]
