# Generated by Django 4.1.1 on 2022-11-20 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0004_imagestype_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image_type',
        ),
        migrations.RemoveField(
            model_name='images',
            name='user',
        ),
        migrations.DeleteModel(
            name='ImagesType',
        ),
    ]
