# Generated by Django 4.1.1 on 2022-11-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0005_remove_images_image_type_remove_images_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicchargers',
            name='available',
        ),
        migrations.AddField(
            model_name='publication',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
