# Generated by Django 4.1.1 on 2022-11-21 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.publication'),
        ),
    ]
