# Generated by Django 4.1.1 on 2022-11-19 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chargers', '0001_initial'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chargers.publication'),
        ),
    ]
