# Generated by Django 4.1.1 on 2022-10-19 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedBookings',
            fields=[
                ('bookings_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookings.bookings')),
            ],
            bases=('bookings.bookings',),
        ),
    ]
