# Generated by Django 4.1.1 on 2022-10-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_finishedbookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
