# Generated by Django 4.1.1 on 2022-11-21 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'BookingStatus',
                'verbose_name_plural': 'BookingsStatus',
            },
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='bookings',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookings.bookingstatus'),
        ),
    ]
