# Generated by Django 4.1.1 on 2022-10-20 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookings_rating_alter_bookings_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='rating',
        ),
    ]
