# Generated by Django 4.1.1 on 2022-11-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
