# Generated by Django 4.1.1 on 2022-11-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_bookings_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='end_date',
            field=models.DateTimeField(default="2020-11-19 18:43:00"),
            preserve_default=False,
        ),
    ]
